import {
  Cloud,
  CloudFog,
  CloudSun,
  Droplets,
  Gauge,
  Layers,
  Mountain,
  RadioTower,
  SunMedium,
  Thermometer,
  Waves,
  Wind,
} from "lucide-react";
import type {
  TimelineStep,
  WeatherLayer,
  WeatherStation,
} from "@/types/weather-platform";

export const stationLayers: WeatherLayer[] = [
  {
    key: "temperature",
    label: "Temperature",
    shortLabel: "Temp",
    kind: "station",
    unit: "°C",
    accent: "#ef4444",
    icon: Thermometer,
  },
  {
    key: "wind",
    label: "Wind",
    shortLabel: "Wind",
    kind: "station",
    unit: "kt",
    accent: "#06b6d4",
    icon: Wind,
  },
  {
    key: "humidity",
    label: "Humidity",
    shortLabel: "RH",
    kind: "station",
    unit: "%",
    accent: "#2563eb",
    icon: Droplets,
  },
  {
    key: "pressure",
    label: "Pressure",
    shortLabel: "SLP",
    kind: "station",
    unit: "hPa",
    accent: "#7c3aed",
    icon: Gauge,
  },
  {
    key: "dewPoint",
    label: "Dew Point",
    shortLabel: "Dew",
    kind: "station",
    unit: "°C",
    accent: "#0891b2",
    icon: CloudFog,
  },
  {
    key: "solarRadiation",
    label: "Solar Radiation",
    shortLabel: "Solar",
    kind: "station",
    unit: "W/m²",
    accent: "#f59e0b",
    icon: SunMedium,
  },
];

export const forecastLayers: WeatherLayer[] = [
  {
    key: "temperatureForecast",
    label: "Temperature Forecast",
    shortLabel: "T+",
    kind: "forecast",
    unit: "°C",
    accent: "#f97316",
    icon: Thermometer,
  },
  {
    key: "humidityForecast",
    label: "Humidity Forecast",
    shortLabel: "RH+",
    kind: "forecast",
    unit: "%",
    accent: "#38bdf8",
    icon: Droplets,
  },
  {
    key: "windForecast",
    label: "Wind Forecast",
    shortLabel: "Wind+",
    kind: "forecast",
    unit: "kt",
    accent: "#14b8a6",
    icon: Wind,
  },
  {
    key: "pressureIsolines",
    label: "Pressure Isolines",
    shortLabel: "ISO",
    kind: "forecast",
    unit: "hPa",
    accent: "#a855f7",
    icon: Waves,
  },
  {
    key: "meanSeaLevelPressure",
    label: "Mean Sea Level Pressure",
    shortLabel: "MSLP",
    kind: "forecast",
    unit: "hPa",
    accent: "#6366f1",
    icon: Gauge,
  },
  {
    key: "geopotential",
    label: "Geopotential",
    shortLabel: "GPH",
    kind: "forecast",
    unit: "dam",
    accent: "#84cc16",
    icon: Mountain,
  },
  {
    key: "dewPointForecast",
    label: "Dew Point Forecast",
    shortLabel: "Dew+",
    kind: "forecast",
    unit: "°C",
    accent: "#22d3ee",
    icon: CloudSun,
  },
  {
    key: "lowCloud",
    label: "Low Cloud",
    shortLabel: "Low",
    kind: "forecast",
    unit: "%",
    accent: "#94a3b8",
    icon: Cloud,
  },
  {
    key: "totalCloud",
    label: "Total Cloud",
    shortLabel: "Cloud",
    kind: "forecast",
    unit: "%",
    accent: "#64748b",
    icon: Layers,
  },
];

export const weatherLayers = [...stationLayers, ...forecastLayers];

export const bangladeshStations: WeatherStation[] = [
  {
    id: "dhaka",
    name: "Dhaka",
    latitude: 23.8103,
    longitude: 90.4125,
    temperature: 31,
    maxTemperature: 34,
    minTemperature: 27,
    humidity: 74,
    pressure: 1007,
    windSpeed: 11,
    windDirection: 165,
    solarRadiation: 640,
    rainfall: 8,
    dewPoint: 25,
  },
  {
    id: "chattogram",
    name: "Chattogram",
    latitude: 22.3569,
    longitude: 91.7832,
    temperature: 29,
    maxTemperature: 32,
    minTemperature: 26,
    humidity: 82,
    pressure: 1009,
    windSpeed: 17,
    windDirection: 210,
    solarRadiation: 560,
    rainfall: 18,
    dewPoint: 26,
  },
  {
    id: "sylhet",
    name: "Sylhet",
    latitude: 24.8949,
    longitude: 91.8687,
    temperature: 28,
    maxTemperature: 31,
    minTemperature: 25,
    humidity: 88,
    pressure: 1008,
    windSpeed: 9,
    windDirection: 130,
    solarRadiation: 470,
    rainfall: 32,
    dewPoint: 26,
  },
  {
    id: "khulna",
    name: "Khulna",
    latitude: 22.8456,
    longitude: 89.5403,
    temperature: 32,
    maxTemperature: 35,
    minTemperature: 27,
    humidity: 76,
    pressure: 1006,
    windSpeed: 13,
    windDirection: 185,
    solarRadiation: 710,
    rainfall: 5,
    dewPoint: 26,
  },
  {
    id: "rajshahi",
    name: "Rajshahi",
    latitude: 24.3745,
    longitude: 88.6042,
    temperature: 33,
    maxTemperature: 36,
    minTemperature: 28,
    humidity: 66,
    pressure: 1005,
    windSpeed: 8,
    windDirection: 245,
    solarRadiation: 760,
    rainfall: 2,
    dewPoint: 24,
  },
  {
    id: "rangpur",
    name: "Rangpur",
    latitude: 25.7439,
    longitude: 89.2752,
    temperature: 30,
    maxTemperature: 33,
    minTemperature: 25,
    humidity: 79,
    pressure: 1008,
    windSpeed: 10,
    windDirection: 155,
    solarRadiation: 590,
    rainfall: 11,
    dewPoint: 25,
  },
  {
    id: "barishal",
    name: "Barishal",
    latitude: 22.701,
    longitude: 90.3535,
    temperature: 30,
    maxTemperature: 33,
    minTemperature: 26,
    humidity: 84,
    pressure: 1008,
    windSpeed: 14,
    windDirection: 195,
    solarRadiation: 530,
    rainfall: 21,
    dewPoint: 26,
  },
  {
    id: "coxsbazar",
    name: "Cox's Bazar",
    latitude: 21.4272,
    longitude: 92.0058,
    temperature: 28,
    maxTemperature: 31,
    minTemperature: 25,
    humidity: 86,
    pressure: 1010,
    windSpeed: 19,
    windDirection: 220,
    solarRadiation: 520,
    rainfall: 27,
    dewPoint: 25,
  },
];

export const timelineSteps: TimelineStep[] = [
  { label: "Now", iso: "2026-08-06T09:00:00+06:00" },
  { label: "+3h", iso: "2026-08-06T12:00:00+06:00" },
  { label: "+6h", iso: "2026-08-06T15:00:00+06:00" },
  { label: "+9h", iso: "2026-08-06T18:00:00+06:00" },
  { label: "+12h", iso: "2026-08-06T21:00:00+06:00" },
  { label: "+18h", iso: "2026-08-07T03:00:00+06:00" },
  { label: "+24h", iso: "2026-08-07T09:00:00+06:00" },
];

export const landingCopy = {
  brand: "BD Weather",
  nav: ["Home", "Features", "About", "Data Sources", "Contact"],
  signIn: "Sign In",
  dashboard: "Dashboard",
  guest: "Guest",
  noStations: "No stations available",
  stationAdmin: "Station Admin",
  observer: "Observer",
  superAdmin: "Super Admin",
  allStations: "Viewing national station network",
  assignedStation: "Viewing assigned station",
  layerSelection: "Weather Layers",
  stationParameters: "Station Parameters",
  forecastLayers: "Forecast Layers",
  activeLayer: "Active Layer",
  opacity: "Opacity",
  timeline: "Timeline",
  speed: "Speed",
  updated: "Updated",
  boundary: "Bangladesh boundary",
  mobileMenu: "Open navigation menu",
  closeMenu: "Close navigation menu",
  theme: "Toggle theme",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  openDrawer: "Open weather layer drawer",
  closeDrawer: "Close weather layer drawer",
  fallbackLayer: "Select a layer",
  stationNetwork: "Station Network",
  forecastOverlay: "Forecast Overlay",
  coordinates: "Coordinates",
  rainfall: "Rainfall",
  solarRadiation: "Solar Radiation",
  windDirection: "Wind Direction",
  windSpeed: "Wind Speed",
  pressure: "Pressure",
  relativeHumidity: "Relative Humidity",
  maxTemperature: "Max Temperature",
  minTemperature: "Min Temperature",
  mapLoading: "Loading Bangladesh weather map",
};

export const stationDefaultIcon = RadioTower;
